### ISSUE TITLE
Notification causes crash in OnePlus

### ISSUE THREAD

**Issue by dmitrilc** [dmitrilc/FreeMediaPlayer#70]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dimitrilc.freemediaplayer, PID: 23849
    android.app.RemoteServiceException: Bad notification(tag=null, id=1) posted from package com.dimitrilc.freemediaplayer, crashing app(uid=10011, pid=23849): Couldn't inflate contentViewsjava.lang.IllegalArgumentException: setShowActionsInCompactView: action 0 out of bounds (max -1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2137)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by dmitrilc** [comment]
Was able to reproduce on API 30 emulator

**Comment by dmitrilc** [comment]
Becase of `action 0 out of bounds`. Might have to add actions BEFORE setting MediaStyle

**Comment by dmitrilc** [comment]
9a536736f689f953973d7143c1b7b4168eb3765b

https://github.com/dmitrilc/FreeMediaPlayer/issues/73
