### ISSUE TITLE
Crash on OnePlus when pressing Next

### ISSUE THREAD

**Issue by dmitrilc** [dmitrilc/FreeMediaPlayer#71]
E/sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.dimitrilc.freemediaplayer, PID: 23851
    java.lang.IllegalStateException: Not implemented
        at androidx.work.CoroutineWorker.getForegroundInfo$suspendImpl(CoroutineWorker.kt:100)
        at androidx.work.CoroutineWorker.getForegroundInfo(Unknown Source:0)
        at androidx.work.CoroutineWorker$getForegroundInfoAsync$1.invokeSuspend(CoroutineWorker.kt:134)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@106b81e, Dispatchers.Default]

**Comment by dmitrilc** [comment]
https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work?hl=en#backwards-compat

**Comment by dmitrilc** [comment]
d241f62ef9865593beba1170fa54d1b55e99130d

https://github.com/dmitrilc/FreeMediaPlayer/issues/73
